//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.Produktion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BalanceProduktion_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion")]
    public partial class BalanceProduktion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WSCreateProdRessLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSCreateTimeStampLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSShowAbsenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSReturnSelectTimeGroupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BalanceProduktion() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_tmp_Produktion_BalanceProduktion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WSCreateProdRessLineCompletedEventHandler WSCreateProdRessLineCompleted;
        
        /// <remarks/>
        public event WSCreateTimeStampLineCompletedEventHandler WSCreateTimeStampLineCompleted;
        
        /// <remarks/>
        public event WSShowAbsenceCompletedEventHandler WSShowAbsenceCompleted;
        
        /// <remarks/>
        public event WSReturnSelectTimeGroupCompletedEventHandler WSReturnSelectTimeGroupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion:WSCreateProdRessLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion", ResponseElementName="WSCreateProdRessLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool WSCreateProdRessLine(string prodResCode, string workCenterCode, System.DateTime startDateTime, System.DateTime endDateTime, string companyCode) {
            object[] results = this.Invoke("WSCreateProdRessLine", new object[] {
                        prodResCode,
                        workCenterCode,
                        startDateTime,
                        endDateTime,
                        companyCode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WSCreateProdRessLineAsync(string prodResCode, string workCenterCode, System.DateTime startDateTime, System.DateTime endDateTime, string companyCode) {
            this.WSCreateProdRessLineAsync(prodResCode, workCenterCode, startDateTime, endDateTime, companyCode, null);
        }
        
        /// <remarks/>
        public void WSCreateProdRessLineAsync(string prodResCode, string workCenterCode, System.DateTime startDateTime, System.DateTime endDateTime, string companyCode, object userState) {
            if ((this.WSCreateProdRessLineOperationCompleted == null)) {
                this.WSCreateProdRessLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSCreateProdRessLineOperationCompleted);
            }
            this.InvokeAsync("WSCreateProdRessLine", new object[] {
                        prodResCode,
                        workCenterCode,
                        startDateTime,
                        endDateTime,
                        companyCode}, this.WSCreateProdRessLineOperationCompleted, userState);
        }
        
        private void OnWSCreateProdRessLineOperationCompleted(object arg) {
            if ((this.WSCreateProdRessLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSCreateProdRessLineCompleted(this, new WSCreateProdRessLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion:WSCreateTimeStampLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion", ResponseElementName="WSCreateTimeStampLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool WSCreateTimeStampLine(string employeeNo, string timeGroupCode, string absenceCode, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime date, [System.Xml.Serialization.XmlElementAttribute(DataType="time")] System.DateTime time, int direction) {
            object[] results = this.Invoke("WSCreateTimeStampLine", new object[] {
                        employeeNo,
                        timeGroupCode,
                        absenceCode,
                        date,
                        time,
                        direction});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WSCreateTimeStampLineAsync(string employeeNo, string timeGroupCode, string absenceCode, System.DateTime date, System.DateTime time, int direction) {
            this.WSCreateTimeStampLineAsync(employeeNo, timeGroupCode, absenceCode, date, time, direction, null);
        }
        
        /// <remarks/>
        public void WSCreateTimeStampLineAsync(string employeeNo, string timeGroupCode, string absenceCode, System.DateTime date, System.DateTime time, int direction, object userState) {
            if ((this.WSCreateTimeStampLineOperationCompleted == null)) {
                this.WSCreateTimeStampLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSCreateTimeStampLineOperationCompleted);
            }
            this.InvokeAsync("WSCreateTimeStampLine", new object[] {
                        employeeNo,
                        timeGroupCode,
                        absenceCode,
                        date,
                        time,
                        direction}, this.WSCreateTimeStampLineOperationCompleted, userState);
        }
        
        private void OnWSCreateTimeStampLineOperationCompleted(object arg) {
            if ((this.WSCreateTimeStampLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSCreateTimeStampLineCompleted(this, new WSCreateTimeStampLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion:WSShowAbsence", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion", ResponseElementName="WSShowAbsence_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool WSShowAbsence(string employeeNo, string timeGroupCode, [System.Xml.Serialization.XmlElementAttribute(DataType="time")] System.DateTime tid, int direction) {
            object[] results = this.Invoke("WSShowAbsence", new object[] {
                        employeeNo,
                        timeGroupCode,
                        tid,
                        direction});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WSShowAbsenceAsync(string employeeNo, string timeGroupCode, System.DateTime tid, int direction) {
            this.WSShowAbsenceAsync(employeeNo, timeGroupCode, tid, direction, null);
        }
        
        /// <remarks/>
        public void WSShowAbsenceAsync(string employeeNo, string timeGroupCode, System.DateTime tid, int direction, object userState) {
            if ((this.WSShowAbsenceOperationCompleted == null)) {
                this.WSShowAbsenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSShowAbsenceOperationCompleted);
            }
            this.InvokeAsync("WSShowAbsence", new object[] {
                        employeeNo,
                        timeGroupCode,
                        tid,
                        direction}, this.WSShowAbsenceOperationCompleted, userState);
        }
        
        private void OnWSShowAbsenceOperationCompleted(object arg) {
            if ((this.WSShowAbsenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSShowAbsenceCompleted(this, new WSShowAbsenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion:WSReturnSelectTimeGroup" +
            "", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion", ResponseElementName="WSReturnSelectTimeGroup_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceProduktion", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool WSReturnSelectTimeGroup() {
            object[] results = this.Invoke("WSReturnSelectTimeGroup", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WSReturnSelectTimeGroupAsync() {
            this.WSReturnSelectTimeGroupAsync(null);
        }
        
        /// <remarks/>
        public void WSReturnSelectTimeGroupAsync(object userState) {
            if ((this.WSReturnSelectTimeGroupOperationCompleted == null)) {
                this.WSReturnSelectTimeGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSReturnSelectTimeGroupOperationCompleted);
            }
            this.InvokeAsync("WSReturnSelectTimeGroup", new object[0], this.WSReturnSelectTimeGroupOperationCompleted, userState);
        }
        
        private void OnWSReturnSelectTimeGroupOperationCompleted(object arg) {
            if ((this.WSReturnSelectTimeGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSReturnSelectTimeGroupCompleted(this, new WSReturnSelectTimeGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WSCreateProdRessLineCompletedEventHandler(object sender, WSCreateProdRessLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSCreateProdRessLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSCreateProdRessLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WSCreateTimeStampLineCompletedEventHandler(object sender, WSCreateTimeStampLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSCreateTimeStampLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSCreateTimeStampLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WSShowAbsenceCompletedEventHandler(object sender, WSShowAbsenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSShowAbsenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSShowAbsenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WSReturnSelectTimeGroupCompletedEventHandler(object sender, WSReturnSelectTimeGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSReturnSelectTimeGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSReturnSelectTimeGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591