#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Resources
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TEST-NAV")]
	public partial class EmployeeConnDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCredin_Employee(Credin_Employee instance);
    partial void UpdateCredin_Employee(Credin_Employee instance);
    partial void DeleteCredin_Employee(Credin_Employee instance);
    #endregion
		
		public EmployeeConnDataContext() : 
				base(global::WindowsFormsApplication1.Properties.Settings.Default.TEST_NAVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeConnDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeConnDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeConnDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeConnDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Credin_Employee> Credin_Employees
		{
			get
			{
				return this.GetTable<Credin_Employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Credin$Employee")]
	public partial class Credin_Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Data.Linq.Binary _timestamp;
		
		private string _No_;
		
		private string _First_Name;
		
		private string _Middle_Name;
		
		private string _Last_Name;
		
		private string _Initials;
		
		private string _Job_Title;
		
		private string _Search_Name;
		
		private string _Address;
		
		private string _Address_2;
		
		private string _City;
		
		private string _Post_Code;
		
		private string _County;
		
		private string _Phone_No_;
		
		private string _Mobile_Phone_No_;
		
		private string _E_Mail;
		
		private string _Alt__Address_Code;
		
		private System.DateTime _Alt__Address_Start_Date;
		
		private System.DateTime _Alt__Address_End_Date;
		
		private System.Data.Linq.Binary _Picture;
		
		private System.DateTime _Birth_Date;
		
		private string _Social_Security_No_;
		
		private string _Union_Code;
		
		private string _Union_Membership_No_;
		
		private int _Sex;
		
		private string _Country_Region_Code;
		
		private string _Manager_No_;
		
		private string _Emplymt__Contract_Code;
		
		private string _Statistics_Group_Code;
		
		private System.DateTime _Employment_Date;
		
		private int _Status;
		
		private System.DateTime _Inactive_Date;
		
		private string _Cause_of_Inactivity_Code;
		
		private System.DateTime _Termination_Date;
		
		private string _Grounds_for_Term__Code;
		
		private string _Global_Dimension_1_Code;
		
		private string _Global_Dimension_2_Code;
		
		private string _Resource_No_;
		
		private System.DateTime _Last_Date_Modified;
		
		private string _Extension;
		
		private string _Pager;
		
		private string _Fax_No_;
		
		private string _Company_E_Mail;
		
		private string _Title;
		
		private string _Salespers__Purch__Code;
		
		private string _No__Series;
		
		private string _Default_Work_Center;
		
		private int _Payed_Advance_Behind;
		
		private int _Pay_Frequency;
		
		private int _Type;
		
		private string _Pay_Agreement_Code;
		
		private string _Pay_Slip_Layout_Name;
		
		private string _Work_Calendar_Code;
		
		private byte _Blocked;
		
		private System.DateTime _Ascension_Date;
		
		private string _Pay_Bracket;
		
		private string _Initial_Pay_Scale;
		
		private System.DateTime _Seniority_Date;
		
		private string _Pension_Code;
		
		private string _Current_Pay_Scale;
		
		private int _Holiday_Accumulation_Basis;
		
		private string _Holiday_Calendar_Code;
		
		private string _G_L_Posting_Group_Code;
		
		private decimal _Employment_Rate____;
		
		private decimal _Evaluation_in_Percent;
		
		private int _Pay_Week;
		
		private System.DateTime _Inactive_Until__Date_;
		
		private string _Pension_Payment_ID;
		
		private System.DateTime _Add__Holiday_Seniority_Date;
		
		private byte _ATP_excempt;
		
		private int _Maternity_Arrangement;
		
		private byte _Pay_Slip_by_E_Mail;
		
		private int _E_Mail_for_Pay_Slip;
		
		private int _Tax_Status;
		
		private string _Production_Unit_No_;
		
		private int _Income_Type;
		
		private string _Payroll_Country_Code;
		
		private byte _Workplace_not_Company_Address;
		
		private byte _Benefit_in_kind_etc_;
		
		private int _ATP_Code;
		
		private byte _Free_Puplic_Transportation;
		
		private int _Extra_Tax__;
		
		private int _Total_Tax__;
		
		private int _Standard_skattekorttype;
		
		private string _SE_No_;
		
		private byte _Tax_excempt;
		
		private byte _AM_Contribution_excempt;
		
		private int _Greenland_municipality;
		
		private int _DA_LO_Development_Fund;
		
		private decimal _Holiday_days_this_year;
		
		private byte _NemKonto;
		
		private byte _Calculate_Holiday_Hours;
		
		private string _Time_Group_Code;
		
		private string _Card_No_;
		
		private string _PIN_Code;
		
		private string _Terminal_Language_Code;
		
		private string _Empl__Time_Stamp_Batch_Name;
		
		private string _Lessor_Portal_ID;
		
		private byte _Lessor_Portal_Active;
		
		private byte _LIF;
		
		private string _Holiday_Reporting_Type_SE_No_;
		
		private byte _ACF;
		
		private int _Language_ID;
		
		private string _Machine_Center_No_;
		
		private string _Profile_Type_Code;
		
		private byte _NemRefusion;
		
		private byte _NemRefusion_Active;
		
		private int _NemRefusion_Spec__Arrangement;
		
		private byte _Payment_During_Absence;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntimestampChanging(System.Data.Linq.Binary value);
    partial void OntimestampChanged();
    partial void OnNo_Changing(string value);
    partial void OnNo_Changed();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnMiddle_NameChanging(string value);
    partial void OnMiddle_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnInitialsChanging(string value);
    partial void OnInitialsChanged();
    partial void OnJob_TitleChanging(string value);
    partial void OnJob_TitleChanged();
    partial void OnSearch_NameChanging(string value);
    partial void OnSearch_NameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnAddress_2Changing(string value);
    partial void OnAddress_2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnPost_CodeChanging(string value);
    partial void OnPost_CodeChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnPhone_No_Changing(string value);
    partial void OnPhone_No_Changed();
    partial void OnMobile_Phone_No_Changing(string value);
    partial void OnMobile_Phone_No_Changed();
    partial void OnE_MailChanging(string value);
    partial void OnE_MailChanged();
    partial void OnAlt__Address_CodeChanging(string value);
    partial void OnAlt__Address_CodeChanged();
    partial void OnAlt__Address_Start_DateChanging(System.DateTime value);
    partial void OnAlt__Address_Start_DateChanged();
    partial void OnAlt__Address_End_DateChanging(System.DateTime value);
    partial void OnAlt__Address_End_DateChanged();
    partial void OnPictureChanging(System.Data.Linq.Binary value);
    partial void OnPictureChanged();
    partial void OnBirth_DateChanging(System.DateTime value);
    partial void OnBirth_DateChanged();
    partial void OnSocial_Security_No_Changing(string value);
    partial void OnSocial_Security_No_Changed();
    partial void OnUnion_CodeChanging(string value);
    partial void OnUnion_CodeChanged();
    partial void OnUnion_Membership_No_Changing(string value);
    partial void OnUnion_Membership_No_Changed();
    partial void OnSexChanging(int value);
    partial void OnSexChanged();
    partial void OnCountry_Region_CodeChanging(string value);
    partial void OnCountry_Region_CodeChanged();
    partial void OnManager_No_Changing(string value);
    partial void OnManager_No_Changed();
    partial void OnEmplymt__Contract_CodeChanging(string value);
    partial void OnEmplymt__Contract_CodeChanged();
    partial void OnStatistics_Group_CodeChanging(string value);
    partial void OnStatistics_Group_CodeChanged();
    partial void OnEmployment_DateChanging(System.DateTime value);
    partial void OnEmployment_DateChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnInactive_DateChanging(System.DateTime value);
    partial void OnInactive_DateChanged();
    partial void OnCause_of_Inactivity_CodeChanging(string value);
    partial void OnCause_of_Inactivity_CodeChanged();
    partial void OnTermination_DateChanging(System.DateTime value);
    partial void OnTermination_DateChanged();
    partial void OnGrounds_for_Term__CodeChanging(string value);
    partial void OnGrounds_for_Term__CodeChanged();
    partial void OnGlobal_Dimension_1_CodeChanging(string value);
    partial void OnGlobal_Dimension_1_CodeChanged();
    partial void OnGlobal_Dimension_2_CodeChanging(string value);
    partial void OnGlobal_Dimension_2_CodeChanged();
    partial void OnResource_No_Changing(string value);
    partial void OnResource_No_Changed();
    partial void OnLast_Date_ModifiedChanging(System.DateTime value);
    partial void OnLast_Date_ModifiedChanged();
    partial void OnExtensionChanging(string value);
    partial void OnExtensionChanged();
    partial void OnPagerChanging(string value);
    partial void OnPagerChanged();
    partial void OnFax_No_Changing(string value);
    partial void OnFax_No_Changed();
    partial void OnCompany_E_MailChanging(string value);
    partial void OnCompany_E_MailChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnSalespers__Purch__CodeChanging(string value);
    partial void OnSalespers__Purch__CodeChanged();
    partial void OnNo__SeriesChanging(string value);
    partial void OnNo__SeriesChanged();
    partial void OnDefault_Work_CenterChanging(string value);
    partial void OnDefault_Work_CenterChanged();
    partial void OnPayed_Advance_BehindChanging(int value);
    partial void OnPayed_Advance_BehindChanged();
    partial void OnPay_FrequencyChanging(int value);
    partial void OnPay_FrequencyChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnPay_Agreement_CodeChanging(string value);
    partial void OnPay_Agreement_CodeChanged();
    partial void OnPay_Slip_Layout_NameChanging(string value);
    partial void OnPay_Slip_Layout_NameChanged();
    partial void OnWork_Calendar_CodeChanging(string value);
    partial void OnWork_Calendar_CodeChanged();
    partial void OnBlockedChanging(byte value);
    partial void OnBlockedChanged();
    partial void OnAscension_DateChanging(System.DateTime value);
    partial void OnAscension_DateChanged();
    partial void OnPay_BracketChanging(string value);
    partial void OnPay_BracketChanged();
    partial void OnInitial_Pay_ScaleChanging(string value);
    partial void OnInitial_Pay_ScaleChanged();
    partial void OnSeniority_DateChanging(System.DateTime value);
    partial void OnSeniority_DateChanged();
    partial void OnPension_CodeChanging(string value);
    partial void OnPension_CodeChanged();
    partial void OnCurrent_Pay_ScaleChanging(string value);
    partial void OnCurrent_Pay_ScaleChanged();
    partial void OnHoliday_Accumulation_BasisChanging(int value);
    partial void OnHoliday_Accumulation_BasisChanged();
    partial void OnHoliday_Calendar_CodeChanging(string value);
    partial void OnHoliday_Calendar_CodeChanged();
    partial void OnG_L_Posting_Group_CodeChanging(string value);
    partial void OnG_L_Posting_Group_CodeChanged();
    partial void OnEmployment_Rate____Changing(decimal value);
    partial void OnEmployment_Rate____Changed();
    partial void OnEvaluation_in_PercentChanging(decimal value);
    partial void OnEvaluation_in_PercentChanged();
    partial void OnPay_WeekChanging(int value);
    partial void OnPay_WeekChanged();
    partial void OnInactive_Until__Date_Changing(System.DateTime value);
    partial void OnInactive_Until__Date_Changed();
    partial void OnPension_Payment_IDChanging(string value);
    partial void OnPension_Payment_IDChanged();
    partial void OnAdd__Holiday_Seniority_DateChanging(System.DateTime value);
    partial void OnAdd__Holiday_Seniority_DateChanged();
    partial void OnATP_excemptChanging(byte value);
    partial void OnATP_excemptChanged();
    partial void OnMaternity_ArrangementChanging(int value);
    partial void OnMaternity_ArrangementChanged();
    partial void OnPay_Slip_by_E_MailChanging(byte value);
    partial void OnPay_Slip_by_E_MailChanged();
    partial void OnE_Mail_for_Pay_SlipChanging(int value);
    partial void OnE_Mail_for_Pay_SlipChanged();
    partial void OnTax_StatusChanging(int value);
    partial void OnTax_StatusChanged();
    partial void OnProduction_Unit_No_Changing(string value);
    partial void OnProduction_Unit_No_Changed();
    partial void OnIncome_TypeChanging(int value);
    partial void OnIncome_TypeChanged();
    partial void OnPayroll_Country_CodeChanging(string value);
    partial void OnPayroll_Country_CodeChanged();
    partial void OnWorkplace_not_Company_AddressChanging(byte value);
    partial void OnWorkplace_not_Company_AddressChanged();
    partial void OnBenefit_in_kind_etc_Changing(byte value);
    partial void OnBenefit_in_kind_etc_Changed();
    partial void OnATP_CodeChanging(int value);
    partial void OnATP_CodeChanged();
    partial void OnFree_Puplic_TransportationChanging(byte value);
    partial void OnFree_Puplic_TransportationChanged();
    partial void OnExtra_Tax__Changing(int value);
    partial void OnExtra_Tax__Changed();
    partial void OnTotal_Tax__Changing(int value);
    partial void OnTotal_Tax__Changed();
    partial void OnStandard_skattekorttypeChanging(int value);
    partial void OnStandard_skattekorttypeChanged();
    partial void OnSE_No_Changing(string value);
    partial void OnSE_No_Changed();
    partial void OnTax_excemptChanging(byte value);
    partial void OnTax_excemptChanged();
    partial void OnAM_Contribution_excemptChanging(byte value);
    partial void OnAM_Contribution_excemptChanged();
    partial void OnGreenland_municipalityChanging(int value);
    partial void OnGreenland_municipalityChanged();
    partial void OnDA_LO_Development_FundChanging(int value);
    partial void OnDA_LO_Development_FundChanged();
    partial void OnHoliday_days_this_yearChanging(decimal value);
    partial void OnHoliday_days_this_yearChanged();
    partial void OnNemKontoChanging(byte value);
    partial void OnNemKontoChanged();
    partial void OnCalculate_Holiday_HoursChanging(byte value);
    partial void OnCalculate_Holiday_HoursChanged();
    partial void OnTime_Group_CodeChanging(string value);
    partial void OnTime_Group_CodeChanged();
    partial void OnCard_No_Changing(string value);
    partial void OnCard_No_Changed();
    partial void OnPIN_CodeChanging(string value);
    partial void OnPIN_CodeChanged();
    partial void OnTerminal_Language_CodeChanging(string value);
    partial void OnTerminal_Language_CodeChanged();
    partial void OnEmpl__Time_Stamp_Batch_NameChanging(string value);
    partial void OnEmpl__Time_Stamp_Batch_NameChanged();
    partial void OnLessor_Portal_IDChanging(string value);
    partial void OnLessor_Portal_IDChanged();
    partial void OnLessor_Portal_ActiveChanging(byte value);
    partial void OnLessor_Portal_ActiveChanged();
    partial void OnLIFChanging(byte value);
    partial void OnLIFChanged();
    partial void OnHoliday_Reporting_Type_SE_No_Changing(string value);
    partial void OnHoliday_Reporting_Type_SE_No_Changed();
    partial void OnACFChanging(byte value);
    partial void OnACFChanged();
    partial void OnLanguage_IDChanging(int value);
    partial void OnLanguage_IDChanged();
    partial void OnMachine_Center_No_Changing(string value);
    partial void OnMachine_Center_No_Changed();
    partial void OnProfile_Type_CodeChanging(string value);
    partial void OnProfile_Type_CodeChanged();
    partial void OnNemRefusionChanging(byte value);
    partial void OnNemRefusionChanged();
    partial void OnNemRefusion_ActiveChanging(byte value);
    partial void OnNemRefusion_ActiveChanged();
    partial void OnNemRefusion_Spec__ArrangementChanging(int value);
    partial void OnNemRefusion_Spec__ArrangementChanged();
    partial void OnPayment_During_AbsenceChanging(byte value);
    partial void OnPayment_During_AbsenceChanged();
    #endregion
		
		public Credin_Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string No_
		{
			get
			{
				return this._No_;
			}
			set
			{
				if ((this._No_ != value))
				{
					this.OnNo_Changing(value);
					this.SendPropertyChanging();
					this._No_ = value;
					this.SendPropertyChanged("No_");
					this.OnNo_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Middle Name]", Storage="_Middle_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Middle_Name
		{
			get
			{
				return this._Middle_Name;
			}
			set
			{
				if ((this._Middle_Name != value))
				{
					this.OnMiddle_NameChanging(value);
					this.SendPropertyChanging();
					this._Middle_Name = value;
					this.SendPropertyChanged("Middle_Name");
					this.OnMiddle_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Initials", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Initials
		{
			get
			{
				return this._Initials;
			}
			set
			{
				if ((this._Initials != value))
				{
					this.OnInitialsChanging(value);
					this.SendPropertyChanging();
					this._Initials = value;
					this.SendPropertyChanged("Initials");
					this.OnInitialsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Job Title]", Storage="_Job_Title", DbType="VarChar(80) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Job_Title
		{
			get
			{
				return this._Job_Title;
			}
			set
			{
				if ((this._Job_Title != value))
				{
					this.OnJob_TitleChanging(value);
					this.SendPropertyChanging();
					this._Job_Title = value;
					this.SendPropertyChanged("Job_Title");
					this.OnJob_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Search Name]", Storage="_Search_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Search_Name
		{
			get
			{
				return this._Search_Name;
			}
			set
			{
				if ((this._Search_Name != value))
				{
					this.OnSearch_NameChanging(value);
					this.SendPropertyChanging();
					this._Search_Name = value;
					this.SendPropertyChanged("Search_Name");
					this.OnSearch_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Address 2]", Storage="_Address_2", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Address_2
		{
			get
			{
				return this._Address_2;
			}
			set
			{
				if ((this._Address_2 != value))
				{
					this.OnAddress_2Changing(value);
					this.SendPropertyChanging();
					this._Address_2 = value;
					this.SendPropertyChanged("Address_2");
					this.OnAddress_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Post Code]", Storage="_Post_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Post_Code
		{
			get
			{
				return this._Post_Code;
			}
			set
			{
				if ((this._Post_Code != value))
				{
					this.OnPost_CodeChanging(value);
					this.SendPropertyChanging();
					this._Post_Code = value;
					this.SendPropertyChanged("Post_Code");
					this.OnPost_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone No_]", Storage="_Phone_No_", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Phone_No_
		{
			get
			{
				return this._Phone_No_;
			}
			set
			{
				if ((this._Phone_No_ != value))
				{
					this.OnPhone_No_Changing(value);
					this.SendPropertyChanging();
					this._Phone_No_ = value;
					this.SendPropertyChanged("Phone_No_");
					this.OnPhone_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mobile Phone No_]", Storage="_Mobile_Phone_No_", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Mobile_Phone_No_
		{
			get
			{
				return this._Mobile_Phone_No_;
			}
			set
			{
				if ((this._Mobile_Phone_No_ != value))
				{
					this.OnMobile_Phone_No_Changing(value);
					this.SendPropertyChanging();
					this._Mobile_Phone_No_ = value;
					this.SendPropertyChanged("Mobile_Phone_No_");
					this.OnMobile_Phone_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-Mail]", Storage="_E_Mail", DbType="VarChar(80) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string E_Mail
		{
			get
			{
				return this._E_Mail;
			}
			set
			{
				if ((this._E_Mail != value))
				{
					this.OnE_MailChanging(value);
					this.SendPropertyChanging();
					this._E_Mail = value;
					this.SendPropertyChanged("E_Mail");
					this.OnE_MailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Alt_ Address Code]", Storage="_Alt__Address_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Alt__Address_Code
		{
			get
			{
				return this._Alt__Address_Code;
			}
			set
			{
				if ((this._Alt__Address_Code != value))
				{
					this.OnAlt__Address_CodeChanging(value);
					this.SendPropertyChanging();
					this._Alt__Address_Code = value;
					this.SendPropertyChanged("Alt__Address_Code");
					this.OnAlt__Address_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Alt_ Address Start Date]", Storage="_Alt__Address_Start_Date", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Alt__Address_Start_Date
		{
			get
			{
				return this._Alt__Address_Start_Date;
			}
			set
			{
				if ((this._Alt__Address_Start_Date != value))
				{
					this.OnAlt__Address_Start_DateChanging(value);
					this.SendPropertyChanging();
					this._Alt__Address_Start_Date = value;
					this.SendPropertyChanged("Alt__Address_Start_Date");
					this.OnAlt__Address_Start_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Alt_ Address End Date]", Storage="_Alt__Address_End_Date", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Alt__Address_End_Date
		{
			get
			{
				return this._Alt__Address_End_Date;
			}
			set
			{
				if ((this._Alt__Address_End_Date != value))
				{
					this.OnAlt__Address_End_DateChanging(value);
					this.SendPropertyChanging();
					this._Alt__Address_End_Date = value;
					this.SendPropertyChanged("Alt__Address_End_Date");
					this.OnAlt__Address_End_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Birth Date]", Storage="_Birth_Date", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Birth_Date
		{
			get
			{
				return this._Birth_Date;
			}
			set
			{
				if ((this._Birth_Date != value))
				{
					this.OnBirth_DateChanging(value);
					this.SendPropertyChanging();
					this._Birth_Date = value;
					this.SendPropertyChanged("Birth_Date");
					this.OnBirth_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Social Security No_]", Storage="_Social_Security_No_", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Social_Security_No_
		{
			get
			{
				return this._Social_Security_No_;
			}
			set
			{
				if ((this._Social_Security_No_ != value))
				{
					this.OnSocial_Security_No_Changing(value);
					this.SendPropertyChanging();
					this._Social_Security_No_ = value;
					this.SendPropertyChanged("Social_Security_No_");
					this.OnSocial_Security_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Union Code]", Storage="_Union_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Union_Code
		{
			get
			{
				return this._Union_Code;
			}
			set
			{
				if ((this._Union_Code != value))
				{
					this.OnUnion_CodeChanging(value);
					this.SendPropertyChanging();
					this._Union_Code = value;
					this.SendPropertyChanged("Union_Code");
					this.OnUnion_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Union Membership No_]", Storage="_Union_Membership_No_", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Union_Membership_No_
		{
			get
			{
				return this._Union_Membership_No_;
			}
			set
			{
				if ((this._Union_Membership_No_ != value))
				{
					this.OnUnion_Membership_No_Changing(value);
					this.SendPropertyChanging();
					this._Union_Membership_No_ = value;
					this.SendPropertyChanged("Union_Membership_No_");
					this.OnUnion_Membership_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Country_Region Code]", Storage="_Country_Region_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Country_Region_Code
		{
			get
			{
				return this._Country_Region_Code;
			}
			set
			{
				if ((this._Country_Region_Code != value))
				{
					this.OnCountry_Region_CodeChanging(value);
					this.SendPropertyChanging();
					this._Country_Region_Code = value;
					this.SendPropertyChanged("Country_Region_Code");
					this.OnCountry_Region_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Manager No_]", Storage="_Manager_No_", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Manager_No_
		{
			get
			{
				return this._Manager_No_;
			}
			set
			{
				if ((this._Manager_No_ != value))
				{
					this.OnManager_No_Changing(value);
					this.SendPropertyChanging();
					this._Manager_No_ = value;
					this.SendPropertyChanged("Manager_No_");
					this.OnManager_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Emplymt_ Contract Code]", Storage="_Emplymt__Contract_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Emplymt__Contract_Code
		{
			get
			{
				return this._Emplymt__Contract_Code;
			}
			set
			{
				if ((this._Emplymt__Contract_Code != value))
				{
					this.OnEmplymt__Contract_CodeChanging(value);
					this.SendPropertyChanging();
					this._Emplymt__Contract_Code = value;
					this.SendPropertyChanged("Emplymt__Contract_Code");
					this.OnEmplymt__Contract_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Statistics Group Code]", Storage="_Statistics_Group_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Statistics_Group_Code
		{
			get
			{
				return this._Statistics_Group_Code;
			}
			set
			{
				if ((this._Statistics_Group_Code != value))
				{
					this.OnStatistics_Group_CodeChanging(value);
					this.SendPropertyChanging();
					this._Statistics_Group_Code = value;
					this.SendPropertyChanged("Statistics_Group_Code");
					this.OnStatistics_Group_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Employment Date]", Storage="_Employment_Date", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Employment_Date
		{
			get
			{
				return this._Employment_Date;
			}
			set
			{
				if ((this._Employment_Date != value))
				{
					this.OnEmployment_DateChanging(value);
					this.SendPropertyChanging();
					this._Employment_Date = value;
					this.SendPropertyChanged("Employment_Date");
					this.OnEmployment_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Inactive Date]", Storage="_Inactive_Date", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Inactive_Date
		{
			get
			{
				return this._Inactive_Date;
			}
			set
			{
				if ((this._Inactive_Date != value))
				{
					this.OnInactive_DateChanging(value);
					this.SendPropertyChanging();
					this._Inactive_Date = value;
					this.SendPropertyChanged("Inactive_Date");
					this.OnInactive_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cause of Inactivity Code]", Storage="_Cause_of_Inactivity_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Cause_of_Inactivity_Code
		{
			get
			{
				return this._Cause_of_Inactivity_Code;
			}
			set
			{
				if ((this._Cause_of_Inactivity_Code != value))
				{
					this.OnCause_of_Inactivity_CodeChanging(value);
					this.SendPropertyChanging();
					this._Cause_of_Inactivity_Code = value;
					this.SendPropertyChanged("Cause_of_Inactivity_Code");
					this.OnCause_of_Inactivity_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Termination Date]", Storage="_Termination_Date", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Termination_Date
		{
			get
			{
				return this._Termination_Date;
			}
			set
			{
				if ((this._Termination_Date != value))
				{
					this.OnTermination_DateChanging(value);
					this.SendPropertyChanging();
					this._Termination_Date = value;
					this.SendPropertyChanged("Termination_Date");
					this.OnTermination_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Grounds for Term_ Code]", Storage="_Grounds_for_Term__Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Grounds_for_Term__Code
		{
			get
			{
				return this._Grounds_for_Term__Code;
			}
			set
			{
				if ((this._Grounds_for_Term__Code != value))
				{
					this.OnGrounds_for_Term__CodeChanging(value);
					this.SendPropertyChanging();
					this._Grounds_for_Term__Code = value;
					this.SendPropertyChanged("Grounds_for_Term__Code");
					this.OnGrounds_for_Term__CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Global Dimension 1 Code]", Storage="_Global_Dimension_1_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Global_Dimension_1_Code
		{
			get
			{
				return this._Global_Dimension_1_Code;
			}
			set
			{
				if ((this._Global_Dimension_1_Code != value))
				{
					this.OnGlobal_Dimension_1_CodeChanging(value);
					this.SendPropertyChanging();
					this._Global_Dimension_1_Code = value;
					this.SendPropertyChanged("Global_Dimension_1_Code");
					this.OnGlobal_Dimension_1_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Global Dimension 2 Code]", Storage="_Global_Dimension_2_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Global_Dimension_2_Code
		{
			get
			{
				return this._Global_Dimension_2_Code;
			}
			set
			{
				if ((this._Global_Dimension_2_Code != value))
				{
					this.OnGlobal_Dimension_2_CodeChanging(value);
					this.SendPropertyChanging();
					this._Global_Dimension_2_Code = value;
					this.SendPropertyChanged("Global_Dimension_2_Code");
					this.OnGlobal_Dimension_2_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Resource No_]", Storage="_Resource_No_", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Resource_No_
		{
			get
			{
				return this._Resource_No_;
			}
			set
			{
				if ((this._Resource_No_ != value))
				{
					this.OnResource_No_Changing(value);
					this.SendPropertyChanging();
					this._Resource_No_ = value;
					this.SendPropertyChanged("Resource_No_");
					this.OnResource_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Date Modified]", Storage="_Last_Date_Modified", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Last_Date_Modified
		{
			get
			{
				return this._Last_Date_Modified;
			}
			set
			{
				if ((this._Last_Date_Modified != value))
				{
					this.OnLast_Date_ModifiedChanging(value);
					this.SendPropertyChanging();
					this._Last_Date_Modified = value;
					this.SendPropertyChanged("Last_Date_Modified");
					this.OnLast_Date_ModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pager", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Pager
		{
			get
			{
				return this._Pager;
			}
			set
			{
				if ((this._Pager != value))
				{
					this.OnPagerChanging(value);
					this.SendPropertyChanging();
					this._Pager = value;
					this.SendPropertyChanged("Pager");
					this.OnPagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fax No_]", Storage="_Fax_No_", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Fax_No_
		{
			get
			{
				return this._Fax_No_;
			}
			set
			{
				if ((this._Fax_No_ != value))
				{
					this.OnFax_No_Changing(value);
					this.SendPropertyChanging();
					this._Fax_No_ = value;
					this.SendPropertyChanged("Fax_No_");
					this.OnFax_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Company E-Mail]", Storage="_Company_E_Mail", DbType="VarChar(80) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Company_E_Mail
		{
			get
			{
				return this._Company_E_Mail;
			}
			set
			{
				if ((this._Company_E_Mail != value))
				{
					this.OnCompany_E_MailChanging(value);
					this.SendPropertyChanging();
					this._Company_E_Mail = value;
					this.SendPropertyChanged("Company_E_Mail");
					this.OnCompany_E_MailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Salespers__Purch_ Code]", Storage="_Salespers__Purch__Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Salespers__Purch__Code
		{
			get
			{
				return this._Salespers__Purch__Code;
			}
			set
			{
				if ((this._Salespers__Purch__Code != value))
				{
					this.OnSalespers__Purch__CodeChanging(value);
					this.SendPropertyChanging();
					this._Salespers__Purch__Code = value;
					this.SendPropertyChanged("Salespers__Purch__Code");
					this.OnSalespers__Purch__CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[No_ Series]", Storage="_No__Series", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string No__Series
		{
			get
			{
				return this._No__Series;
			}
			set
			{
				if ((this._No__Series != value))
				{
					this.OnNo__SeriesChanging(value);
					this.SendPropertyChanging();
					this._No__Series = value;
					this.SendPropertyChanged("No__Series");
					this.OnNo__SeriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Default Work Center]", Storage="_Default_Work_Center", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Default_Work_Center
		{
			get
			{
				return this._Default_Work_Center;
			}
			set
			{
				if ((this._Default_Work_Center != value))
				{
					this.OnDefault_Work_CenterChanging(value);
					this.SendPropertyChanging();
					this._Default_Work_Center = value;
					this.SendPropertyChanged("Default_Work_Center");
					this.OnDefault_Work_CenterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Payed Advance_Behind]", Storage="_Payed_Advance_Behind", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Payed_Advance_Behind
		{
			get
			{
				return this._Payed_Advance_Behind;
			}
			set
			{
				if ((this._Payed_Advance_Behind != value))
				{
					this.OnPayed_Advance_BehindChanging(value);
					this.SendPropertyChanging();
					this._Payed_Advance_Behind = value;
					this.SendPropertyChanged("Payed_Advance_Behind");
					this.OnPayed_Advance_BehindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pay Frequency]", Storage="_Pay_Frequency", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Pay_Frequency
		{
			get
			{
				return this._Pay_Frequency;
			}
			set
			{
				if ((this._Pay_Frequency != value))
				{
					this.OnPay_FrequencyChanging(value);
					this.SendPropertyChanging();
					this._Pay_Frequency = value;
					this.SendPropertyChanged("Pay_Frequency");
					this.OnPay_FrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pay Agreement Code]", Storage="_Pay_Agreement_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Pay_Agreement_Code
		{
			get
			{
				return this._Pay_Agreement_Code;
			}
			set
			{
				if ((this._Pay_Agreement_Code != value))
				{
					this.OnPay_Agreement_CodeChanging(value);
					this.SendPropertyChanging();
					this._Pay_Agreement_Code = value;
					this.SendPropertyChanged("Pay_Agreement_Code");
					this.OnPay_Agreement_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pay Slip Layout Name]", Storage="_Pay_Slip_Layout_Name", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Pay_Slip_Layout_Name
		{
			get
			{
				return this._Pay_Slip_Layout_Name;
			}
			set
			{
				if ((this._Pay_Slip_Layout_Name != value))
				{
					this.OnPay_Slip_Layout_NameChanging(value);
					this.SendPropertyChanging();
					this._Pay_Slip_Layout_Name = value;
					this.SendPropertyChanged("Pay_Slip_Layout_Name");
					this.OnPay_Slip_Layout_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Work Calendar Code]", Storage="_Work_Calendar_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Work_Calendar_Code
		{
			get
			{
				return this._Work_Calendar_Code;
			}
			set
			{
				if ((this._Work_Calendar_Code != value))
				{
					this.OnWork_Calendar_CodeChanging(value);
					this.SendPropertyChanging();
					this._Work_Calendar_Code = value;
					this.SendPropertyChanged("Work_Calendar_Code");
					this.OnWork_Calendar_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blocked", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Blocked
		{
			get
			{
				return this._Blocked;
			}
			set
			{
				if ((this._Blocked != value))
				{
					this.OnBlockedChanging(value);
					this.SendPropertyChanging();
					this._Blocked = value;
					this.SendPropertyChanged("Blocked");
					this.OnBlockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ascension Date]", Storage="_Ascension_Date", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Ascension_Date
		{
			get
			{
				return this._Ascension_Date;
			}
			set
			{
				if ((this._Ascension_Date != value))
				{
					this.OnAscension_DateChanging(value);
					this.SendPropertyChanging();
					this._Ascension_Date = value;
					this.SendPropertyChanged("Ascension_Date");
					this.OnAscension_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pay Bracket]", Storage="_Pay_Bracket", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Pay_Bracket
		{
			get
			{
				return this._Pay_Bracket;
			}
			set
			{
				if ((this._Pay_Bracket != value))
				{
					this.OnPay_BracketChanging(value);
					this.SendPropertyChanging();
					this._Pay_Bracket = value;
					this.SendPropertyChanged("Pay_Bracket");
					this.OnPay_BracketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Initial Pay Scale]", Storage="_Initial_Pay_Scale", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Initial_Pay_Scale
		{
			get
			{
				return this._Initial_Pay_Scale;
			}
			set
			{
				if ((this._Initial_Pay_Scale != value))
				{
					this.OnInitial_Pay_ScaleChanging(value);
					this.SendPropertyChanging();
					this._Initial_Pay_Scale = value;
					this.SendPropertyChanged("Initial_Pay_Scale");
					this.OnInitial_Pay_ScaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Seniority Date]", Storage="_Seniority_Date", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Seniority_Date
		{
			get
			{
				return this._Seniority_Date;
			}
			set
			{
				if ((this._Seniority_Date != value))
				{
					this.OnSeniority_DateChanging(value);
					this.SendPropertyChanging();
					this._Seniority_Date = value;
					this.SendPropertyChanged("Seniority_Date");
					this.OnSeniority_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pension Code]", Storage="_Pension_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Pension_Code
		{
			get
			{
				return this._Pension_Code;
			}
			set
			{
				if ((this._Pension_Code != value))
				{
					this.OnPension_CodeChanging(value);
					this.SendPropertyChanging();
					this._Pension_Code = value;
					this.SendPropertyChanged("Pension_Code");
					this.OnPension_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Current Pay Scale]", Storage="_Current_Pay_Scale", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Current_Pay_Scale
		{
			get
			{
				return this._Current_Pay_Scale;
			}
			set
			{
				if ((this._Current_Pay_Scale != value))
				{
					this.OnCurrent_Pay_ScaleChanging(value);
					this.SendPropertyChanging();
					this._Current_Pay_Scale = value;
					this.SendPropertyChanged("Current_Pay_Scale");
					this.OnCurrent_Pay_ScaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Holiday Accumulation Basis]", Storage="_Holiday_Accumulation_Basis", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Holiday_Accumulation_Basis
		{
			get
			{
				return this._Holiday_Accumulation_Basis;
			}
			set
			{
				if ((this._Holiday_Accumulation_Basis != value))
				{
					this.OnHoliday_Accumulation_BasisChanging(value);
					this.SendPropertyChanging();
					this._Holiday_Accumulation_Basis = value;
					this.SendPropertyChanged("Holiday_Accumulation_Basis");
					this.OnHoliday_Accumulation_BasisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Holiday Calendar Code]", Storage="_Holiday_Calendar_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Holiday_Calendar_Code
		{
			get
			{
				return this._Holiday_Calendar_Code;
			}
			set
			{
				if ((this._Holiday_Calendar_Code != value))
				{
					this.OnHoliday_Calendar_CodeChanging(value);
					this.SendPropertyChanging();
					this._Holiday_Calendar_Code = value;
					this.SendPropertyChanged("Holiday_Calendar_Code");
					this.OnHoliday_Calendar_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[G_L Posting Group Code]", Storage="_G_L_Posting_Group_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string G_L_Posting_Group_Code
		{
			get
			{
				return this._G_L_Posting_Group_Code;
			}
			set
			{
				if ((this._G_L_Posting_Group_Code != value))
				{
					this.OnG_L_Posting_Group_CodeChanging(value);
					this.SendPropertyChanging();
					this._G_L_Posting_Group_Code = value;
					this.SendPropertyChanged("G_L_Posting_Group_Code");
					this.OnG_L_Posting_Group_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Employment Rate (%)]", Storage="_Employment_Rate____", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Employment_Rate____
		{
			get
			{
				return this._Employment_Rate____;
			}
			set
			{
				if ((this._Employment_Rate____ != value))
				{
					this.OnEmployment_Rate____Changing(value);
					this.SendPropertyChanging();
					this._Employment_Rate____ = value;
					this.SendPropertyChanged("Employment_Rate____");
					this.OnEmployment_Rate____Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Evaluation in Percent]", Storage="_Evaluation_in_Percent", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Evaluation_in_Percent
		{
			get
			{
				return this._Evaluation_in_Percent;
			}
			set
			{
				if ((this._Evaluation_in_Percent != value))
				{
					this.OnEvaluation_in_PercentChanging(value);
					this.SendPropertyChanging();
					this._Evaluation_in_Percent = value;
					this.SendPropertyChanged("Evaluation_in_Percent");
					this.OnEvaluation_in_PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pay Week]", Storage="_Pay_Week", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Pay_Week
		{
			get
			{
				return this._Pay_Week;
			}
			set
			{
				if ((this._Pay_Week != value))
				{
					this.OnPay_WeekChanging(value);
					this.SendPropertyChanging();
					this._Pay_Week = value;
					this.SendPropertyChanged("Pay_Week");
					this.OnPay_WeekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Inactive Until (Date)]", Storage="_Inactive_Until__Date_", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Inactive_Until__Date_
		{
			get
			{
				return this._Inactive_Until__Date_;
			}
			set
			{
				if ((this._Inactive_Until__Date_ != value))
				{
					this.OnInactive_Until__Date_Changing(value);
					this.SendPropertyChanging();
					this._Inactive_Until__Date_ = value;
					this.SendPropertyChanged("Inactive_Until__Date_");
					this.OnInactive_Until__Date_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pension Payment ID]", Storage="_Pension_Payment_ID", DbType="VarChar(5) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Pension_Payment_ID
		{
			get
			{
				return this._Pension_Payment_ID;
			}
			set
			{
				if ((this._Pension_Payment_ID != value))
				{
					this.OnPension_Payment_IDChanging(value);
					this.SendPropertyChanging();
					this._Pension_Payment_ID = value;
					this.SendPropertyChanged("Pension_Payment_ID");
					this.OnPension_Payment_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Add_ Holiday Seniority Date]", Storage="_Add__Holiday_Seniority_Date", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Add__Holiday_Seniority_Date
		{
			get
			{
				return this._Add__Holiday_Seniority_Date;
			}
			set
			{
				if ((this._Add__Holiday_Seniority_Date != value))
				{
					this.OnAdd__Holiday_Seniority_DateChanging(value);
					this.SendPropertyChanging();
					this._Add__Holiday_Seniority_Date = value;
					this.SendPropertyChanged("Add__Holiday_Seniority_Date");
					this.OnAdd__Holiday_Seniority_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ATP excempt]", Storage="_ATP_excempt", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte ATP_excempt
		{
			get
			{
				return this._ATP_excempt;
			}
			set
			{
				if ((this._ATP_excempt != value))
				{
					this.OnATP_excemptChanging(value);
					this.SendPropertyChanging();
					this._ATP_excempt = value;
					this.SendPropertyChanged("ATP_excempt");
					this.OnATP_excemptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Maternity Arrangement]", Storage="_Maternity_Arrangement", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Maternity_Arrangement
		{
			get
			{
				return this._Maternity_Arrangement;
			}
			set
			{
				if ((this._Maternity_Arrangement != value))
				{
					this.OnMaternity_ArrangementChanging(value);
					this.SendPropertyChanging();
					this._Maternity_Arrangement = value;
					this.SendPropertyChanged("Maternity_Arrangement");
					this.OnMaternity_ArrangementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pay Slip by E-Mail]", Storage="_Pay_Slip_by_E_Mail", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Pay_Slip_by_E_Mail
		{
			get
			{
				return this._Pay_Slip_by_E_Mail;
			}
			set
			{
				if ((this._Pay_Slip_by_E_Mail != value))
				{
					this.OnPay_Slip_by_E_MailChanging(value);
					this.SendPropertyChanging();
					this._Pay_Slip_by_E_Mail = value;
					this.SendPropertyChanged("Pay_Slip_by_E_Mail");
					this.OnPay_Slip_by_E_MailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-Mail for Pay Slip]", Storage="_E_Mail_for_Pay_Slip", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int E_Mail_for_Pay_Slip
		{
			get
			{
				return this._E_Mail_for_Pay_Slip;
			}
			set
			{
				if ((this._E_Mail_for_Pay_Slip != value))
				{
					this.OnE_Mail_for_Pay_SlipChanging(value);
					this.SendPropertyChanging();
					this._E_Mail_for_Pay_Slip = value;
					this.SendPropertyChanged("E_Mail_for_Pay_Slip");
					this.OnE_Mail_for_Pay_SlipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tax Status]", Storage="_Tax_Status", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Tax_Status
		{
			get
			{
				return this._Tax_Status;
			}
			set
			{
				if ((this._Tax_Status != value))
				{
					this.OnTax_StatusChanging(value);
					this.SendPropertyChanging();
					this._Tax_Status = value;
					this.SendPropertyChanged("Tax_Status");
					this.OnTax_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Production Unit No_]", Storage="_Production_Unit_No_", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Production_Unit_No_
		{
			get
			{
				return this._Production_Unit_No_;
			}
			set
			{
				if ((this._Production_Unit_No_ != value))
				{
					this.OnProduction_Unit_No_Changing(value);
					this.SendPropertyChanging();
					this._Production_Unit_No_ = value;
					this.SendPropertyChanged("Production_Unit_No_");
					this.OnProduction_Unit_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Income Type]", Storage="_Income_Type", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Income_Type
		{
			get
			{
				return this._Income_Type;
			}
			set
			{
				if ((this._Income_Type != value))
				{
					this.OnIncome_TypeChanging(value);
					this.SendPropertyChanging();
					this._Income_Type = value;
					this.SendPropertyChanged("Income_Type");
					this.OnIncome_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Payroll Country Code]", Storage="_Payroll_Country_Code", DbType="VarChar(2) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Payroll_Country_Code
		{
			get
			{
				return this._Payroll_Country_Code;
			}
			set
			{
				if ((this._Payroll_Country_Code != value))
				{
					this.OnPayroll_Country_CodeChanging(value);
					this.SendPropertyChanging();
					this._Payroll_Country_Code = value;
					this.SendPropertyChanged("Payroll_Country_Code");
					this.OnPayroll_Country_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Workplace not Company Address]", Storage="_Workplace_not_Company_Address", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Workplace_not_Company_Address
		{
			get
			{
				return this._Workplace_not_Company_Address;
			}
			set
			{
				if ((this._Workplace_not_Company_Address != value))
				{
					this.OnWorkplace_not_Company_AddressChanging(value);
					this.SendPropertyChanging();
					this._Workplace_not_Company_Address = value;
					this.SendPropertyChanged("Workplace_not_Company_Address");
					this.OnWorkplace_not_Company_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Benefit in kind etc_]", Storage="_Benefit_in_kind_etc_", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Benefit_in_kind_etc_
		{
			get
			{
				return this._Benefit_in_kind_etc_;
			}
			set
			{
				if ((this._Benefit_in_kind_etc_ != value))
				{
					this.OnBenefit_in_kind_etc_Changing(value);
					this.SendPropertyChanging();
					this._Benefit_in_kind_etc_ = value;
					this.SendPropertyChanged("Benefit_in_kind_etc_");
					this.OnBenefit_in_kind_etc_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ATP Code]", Storage="_ATP_Code", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int ATP_Code
		{
			get
			{
				return this._ATP_Code;
			}
			set
			{
				if ((this._ATP_Code != value))
				{
					this.OnATP_CodeChanging(value);
					this.SendPropertyChanging();
					this._ATP_Code = value;
					this.SendPropertyChanged("ATP_Code");
					this.OnATP_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Free Puplic Transportation]", Storage="_Free_Puplic_Transportation", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Free_Puplic_Transportation
		{
			get
			{
				return this._Free_Puplic_Transportation;
			}
			set
			{
				if ((this._Free_Puplic_Transportation != value))
				{
					this.OnFree_Puplic_TransportationChanging(value);
					this.SendPropertyChanging();
					this._Free_Puplic_Transportation = value;
					this.SendPropertyChanged("Free_Puplic_Transportation");
					this.OnFree_Puplic_TransportationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Extra Tax %]", Storage="_Extra_Tax__", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Extra_Tax__
		{
			get
			{
				return this._Extra_Tax__;
			}
			set
			{
				if ((this._Extra_Tax__ != value))
				{
					this.OnExtra_Tax__Changing(value);
					this.SendPropertyChanging();
					this._Extra_Tax__ = value;
					this.SendPropertyChanged("Extra_Tax__");
					this.OnExtra_Tax__Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total Tax %]", Storage="_Total_Tax__", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Total_Tax__
		{
			get
			{
				return this._Total_Tax__;
			}
			set
			{
				if ((this._Total_Tax__ != value))
				{
					this.OnTotal_Tax__Changing(value);
					this.SendPropertyChanging();
					this._Total_Tax__ = value;
					this.SendPropertyChanged("Total_Tax__");
					this.OnTotal_Tax__Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Standard skattekorttype]", Storage="_Standard_skattekorttype", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Standard_skattekorttype
		{
			get
			{
				return this._Standard_skattekorttype;
			}
			set
			{
				if ((this._Standard_skattekorttype != value))
				{
					this.OnStandard_skattekorttypeChanging(value);
					this.SendPropertyChanging();
					this._Standard_skattekorttype = value;
					this.SendPropertyChanged("Standard_skattekorttype");
					this.OnStandard_skattekorttypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SE-No_]", Storage="_SE_No_", DbType="VarChar(8) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string SE_No_
		{
			get
			{
				return this._SE_No_;
			}
			set
			{
				if ((this._SE_No_ != value))
				{
					this.OnSE_No_Changing(value);
					this.SendPropertyChanging();
					this._SE_No_ = value;
					this.SendPropertyChanged("SE_No_");
					this.OnSE_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tax excempt]", Storage="_Tax_excempt", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Tax_excempt
		{
			get
			{
				return this._Tax_excempt;
			}
			set
			{
				if ((this._Tax_excempt != value))
				{
					this.OnTax_excemptChanging(value);
					this.SendPropertyChanging();
					this._Tax_excempt = value;
					this.SendPropertyChanged("Tax_excempt");
					this.OnTax_excemptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[AM Contribution excempt]", Storage="_AM_Contribution_excempt", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte AM_Contribution_excempt
		{
			get
			{
				return this._AM_Contribution_excempt;
			}
			set
			{
				if ((this._AM_Contribution_excempt != value))
				{
					this.OnAM_Contribution_excemptChanging(value);
					this.SendPropertyChanging();
					this._AM_Contribution_excempt = value;
					this.SendPropertyChanged("AM_Contribution_excempt");
					this.OnAM_Contribution_excemptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Greenland municipality]", Storage="_Greenland_municipality", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Greenland_municipality
		{
			get
			{
				return this._Greenland_municipality;
			}
			set
			{
				if ((this._Greenland_municipality != value))
				{
					this.OnGreenland_municipalityChanging(value);
					this.SendPropertyChanging();
					this._Greenland_municipality = value;
					this.SendPropertyChanged("Greenland_municipality");
					this.OnGreenland_municipalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DA_LO Development Fund]", Storage="_DA_LO_Development_Fund", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DA_LO_Development_Fund
		{
			get
			{
				return this._DA_LO_Development_Fund;
			}
			set
			{
				if ((this._DA_LO_Development_Fund != value))
				{
					this.OnDA_LO_Development_FundChanging(value);
					this.SendPropertyChanging();
					this._DA_LO_Development_Fund = value;
					this.SendPropertyChanged("DA_LO_Development_Fund");
					this.OnDA_LO_Development_FundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Holiday days this year]", Storage="_Holiday_days_this_year", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Holiday_days_this_year
		{
			get
			{
				return this._Holiday_days_this_year;
			}
			set
			{
				if ((this._Holiday_days_this_year != value))
				{
					this.OnHoliday_days_this_yearChanging(value);
					this.SendPropertyChanging();
					this._Holiday_days_this_year = value;
					this.SendPropertyChanged("Holiday_days_this_year");
					this.OnHoliday_days_this_yearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NemKonto", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte NemKonto
		{
			get
			{
				return this._NemKonto;
			}
			set
			{
				if ((this._NemKonto != value))
				{
					this.OnNemKontoChanging(value);
					this.SendPropertyChanging();
					this._NemKonto = value;
					this.SendPropertyChanged("NemKonto");
					this.OnNemKontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Calculate Holiday Hours]", Storage="_Calculate_Holiday_Hours", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Calculate_Holiday_Hours
		{
			get
			{
				return this._Calculate_Holiday_Hours;
			}
			set
			{
				if ((this._Calculate_Holiday_Hours != value))
				{
					this.OnCalculate_Holiday_HoursChanging(value);
					this.SendPropertyChanging();
					this._Calculate_Holiday_Hours = value;
					this.SendPropertyChanged("Calculate_Holiday_Hours");
					this.OnCalculate_Holiday_HoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Time Group Code]", Storage="_Time_Group_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Time_Group_Code
		{
			get
			{
				return this._Time_Group_Code;
			}
			set
			{
				if ((this._Time_Group_Code != value))
				{
					this.OnTime_Group_CodeChanging(value);
					this.SendPropertyChanging();
					this._Time_Group_Code = value;
					this.SendPropertyChanged("Time_Group_Code");
					this.OnTime_Group_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Card No_]", Storage="_Card_No_", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Card_No_
		{
			get
			{
				return this._Card_No_;
			}
			set
			{
				if ((this._Card_No_ != value))
				{
					this.OnCard_No_Changing(value);
					this.SendPropertyChanging();
					this._Card_No_ = value;
					this.SendPropertyChanged("Card_No_");
					this.OnCard_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PIN Code]", Storage="_PIN_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string PIN_Code
		{
			get
			{
				return this._PIN_Code;
			}
			set
			{
				if ((this._PIN_Code != value))
				{
					this.OnPIN_CodeChanging(value);
					this.SendPropertyChanging();
					this._PIN_Code = value;
					this.SendPropertyChanged("PIN_Code");
					this.OnPIN_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Terminal Language Code]", Storage="_Terminal_Language_Code", DbType="VarChar(3) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Terminal_Language_Code
		{
			get
			{
				return this._Terminal_Language_Code;
			}
			set
			{
				if ((this._Terminal_Language_Code != value))
				{
					this.OnTerminal_Language_CodeChanging(value);
					this.SendPropertyChanging();
					this._Terminal_Language_Code = value;
					this.SendPropertyChanged("Terminal_Language_Code");
					this.OnTerminal_Language_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Empl_ Time Stamp Batch Name]", Storage="_Empl__Time_Stamp_Batch_Name", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Empl__Time_Stamp_Batch_Name
		{
			get
			{
				return this._Empl__Time_Stamp_Batch_Name;
			}
			set
			{
				if ((this._Empl__Time_Stamp_Batch_Name != value))
				{
					this.OnEmpl__Time_Stamp_Batch_NameChanging(value);
					this.SendPropertyChanging();
					this._Empl__Time_Stamp_Batch_Name = value;
					this.SendPropertyChanged("Empl__Time_Stamp_Batch_Name");
					this.OnEmpl__Time_Stamp_Batch_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Lessor Portal ID]", Storage="_Lessor_Portal_ID", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Lessor_Portal_ID
		{
			get
			{
				return this._Lessor_Portal_ID;
			}
			set
			{
				if ((this._Lessor_Portal_ID != value))
				{
					this.OnLessor_Portal_IDChanging(value);
					this.SendPropertyChanging();
					this._Lessor_Portal_ID = value;
					this.SendPropertyChanged("Lessor_Portal_ID");
					this.OnLessor_Portal_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Lessor Portal Active]", Storage="_Lessor_Portal_Active", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Lessor_Portal_Active
		{
			get
			{
				return this._Lessor_Portal_Active;
			}
			set
			{
				if ((this._Lessor_Portal_Active != value))
				{
					this.OnLessor_Portal_ActiveChanging(value);
					this.SendPropertyChanging();
					this._Lessor_Portal_Active = value;
					this.SendPropertyChanged("Lessor_Portal_Active");
					this.OnLessor_Portal_ActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIF", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte LIF
		{
			get
			{
				return this._LIF;
			}
			set
			{
				if ((this._LIF != value))
				{
					this.OnLIFChanging(value);
					this.SendPropertyChanging();
					this._LIF = value;
					this.SendPropertyChanged("LIF");
					this.OnLIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Holiday Reporting Type SE-No_]", Storage="_Holiday_Reporting_Type_SE_No_", DbType="VarChar(8) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Holiday_Reporting_Type_SE_No_
		{
			get
			{
				return this._Holiday_Reporting_Type_SE_No_;
			}
			set
			{
				if ((this._Holiday_Reporting_Type_SE_No_ != value))
				{
					this.OnHoliday_Reporting_Type_SE_No_Changing(value);
					this.SendPropertyChanging();
					this._Holiday_Reporting_Type_SE_No_ = value;
					this.SendPropertyChanged("Holiday_Reporting_Type_SE_No_");
					this.OnHoliday_Reporting_Type_SE_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACF", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte ACF
		{
			get
			{
				return this._ACF;
			}
			set
			{
				if ((this._ACF != value))
				{
					this.OnACFChanging(value);
					this.SendPropertyChanging();
					this._ACF = value;
					this.SendPropertyChanged("ACF");
					this.OnACFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Language ID]", Storage="_Language_ID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Language_ID
		{
			get
			{
				return this._Language_ID;
			}
			set
			{
				if ((this._Language_ID != value))
				{
					this.OnLanguage_IDChanging(value);
					this.SendPropertyChanging();
					this._Language_ID = value;
					this.SendPropertyChanged("Language_ID");
					this.OnLanguage_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Machine Center No_]", Storage="_Machine_Center_No_", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Machine_Center_No_
		{
			get
			{
				return this._Machine_Center_No_;
			}
			set
			{
				if ((this._Machine_Center_No_ != value))
				{
					this.OnMachine_Center_No_Changing(value);
					this.SendPropertyChanging();
					this._Machine_Center_No_ = value;
					this.SendPropertyChanged("Machine_Center_No_");
					this.OnMachine_Center_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Profile Type Code]", Storage="_Profile_Type_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Profile_Type_Code
		{
			get
			{
				return this._Profile_Type_Code;
			}
			set
			{
				if ((this._Profile_Type_Code != value))
				{
					this.OnProfile_Type_CodeChanging(value);
					this.SendPropertyChanging();
					this._Profile_Type_Code = value;
					this.SendPropertyChanged("Profile_Type_Code");
					this.OnProfile_Type_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NemRefusion", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte NemRefusion
		{
			get
			{
				return this._NemRefusion;
			}
			set
			{
				if ((this._NemRefusion != value))
				{
					this.OnNemRefusionChanging(value);
					this.SendPropertyChanging();
					this._NemRefusion = value;
					this.SendPropertyChanged("NemRefusion");
					this.OnNemRefusionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[NemRefusion Active]", Storage="_NemRefusion_Active", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte NemRefusion_Active
		{
			get
			{
				return this._NemRefusion_Active;
			}
			set
			{
				if ((this._NemRefusion_Active != value))
				{
					this.OnNemRefusion_ActiveChanging(value);
					this.SendPropertyChanging();
					this._NemRefusion_Active = value;
					this.SendPropertyChanged("NemRefusion_Active");
					this.OnNemRefusion_ActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[NemRefusion Spec_ Arrangement]", Storage="_NemRefusion_Spec__Arrangement", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int NemRefusion_Spec__Arrangement
		{
			get
			{
				return this._NemRefusion_Spec__Arrangement;
			}
			set
			{
				if ((this._NemRefusion_Spec__Arrangement != value))
				{
					this.OnNemRefusion_Spec__ArrangementChanging(value);
					this.SendPropertyChanging();
					this._NemRefusion_Spec__Arrangement = value;
					this.SendPropertyChanged("NemRefusion_Spec__Arrangement");
					this.OnNemRefusion_Spec__ArrangementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Payment During Absence]", Storage="_Payment_During_Absence", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Payment_During_Absence
		{
			get
			{
				return this._Payment_During_Absence;
			}
			set
			{
				if ((this._Payment_During_Absence != value))
				{
					this.OnPayment_During_AbsenceChanging(value);
					this.SendPropertyChanging();
					this._Payment_During_Absence = value;
					this.SendPropertyChanged("Payment_During_Absence");
					this.OnPayment_During_AbsenceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
