<?xml version="1.0" encoding="utf-8"?><Database Name="TEST-NAV" Class="WorkCenterConnDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SQLNAV\SQLNAV;Initial Catalog=TEST-NAV;Integrated Security=True" SettingsObjectName="WindowsFormsApplication1.Properties.Settings" SettingsPropertyName="TEST_NAVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Credin$Work Center]" Member="Credin_Work_Centers">
    <Type Name="Credin_Work_Center">
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="No_" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[Search Name]" Member="Search_Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[Name 2]" Member="Name_2" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[Address 2]" Member="Address_2" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[Post Code]" Member="Post_Code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[Alternate Work Center]" Member="Alternate_Work_Center" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[Work Center Group Code]" Member="Work_Center_Group_Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="[Global Dimension 1 Code]" Member="Global_Dimension_1_Code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[Global Dimension 2 Code]" Member="Global_Dimension_2_Code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[Subcontractor No_]" Member="Subcontractor_No_" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[Direct Unit Cost]" Member="Direct_Unit_Cost" Type="System.Decimal" DbType="Decimal(38,20) NOT NULL" CanBeNull="false" />
      <Column Name="[Indirect Cost %]" Member="Indirect_Cost__" Type="System.Decimal" DbType="Decimal(38,20) NOT NULL" CanBeNull="false" />
      <Column Name="[Unit Cost]" Member="Unit_Cost" Type="System.Decimal" DbType="Decimal(38,20) NOT NULL" CanBeNull="false" />
      <Column Name="[Queue Time]" Member="Queue_Time" Type="System.Decimal" DbType="Decimal(38,20) NOT NULL" CanBeNull="false" />
      <Column Name="[Queue Time Unit of Meas_ Code]" Member="Queue_Time_Unit_of_Meas__Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="[Last Date Modified]" Member="Last_Date_Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Unit of Measure Code]" Member="Unit_of_Measure_Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.Decimal" DbType="Decimal(38,20) NOT NULL" CanBeNull="false" />
      <Column Name="Efficiency" Type="System.Decimal" DbType="Decimal(38,20) NOT NULL" CanBeNull="false" />
      <Column Name="[Maximum Efficiency]" Member="Maximum_Efficiency" Type="System.Decimal" DbType="Decimal(38,20) NOT NULL" CanBeNull="false" />
      <Column Name="[Minimum Efficiency]" Member="Minimum_Efficiency" Type="System.Decimal" DbType="Decimal(38,20) NOT NULL" CanBeNull="false" />
      <Column Name="[Calendar Rounding Precision]" Member="Calendar_Rounding_Precision" Type="System.Decimal" DbType="Decimal(38,20) NOT NULL" CanBeNull="false" />
      <Column Name="[Simulation Type]" Member="Simulation_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Shop Calendar Code]" Member="Shop_Calendar_Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Blocked" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="[Unit Cost Calculation]" Member="Unit_Cost_Calculation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Specific Unit Cost]" Member="Specific_Unit_Cost" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="[Consolidated Calendar]" Member="Consolidated_Calendar" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="[Flushing Method]" Member="Flushing_Method" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[No_ Series]" Member="No__Series" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="[Overhead Rate]" Member="Overhead_Rate" Type="System.Decimal" DbType="Decimal(38,20) NOT NULL" CanBeNull="false" />
      <Column Name="[Gen_ Prod_ Posting Group]" Member="Gen__Prod__Posting_Group" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="County" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[Country Code]" Member="Country_Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="[Vis i afgangsvindue]" Member="Vis_i_afgangsvindue" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="[Terminal reg_ no_]" Member="Terminal_reg__no_" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="[Registrer vægt fra Anlæg]" Member="Registrer_vægt_fra_Anlæg" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Sortering" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Manuel Produktionsrækkefølge]" Member="Manuel_Produktionsrækkefølge" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>