#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Resources
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TEST-NAV")]
	public partial class WorkCenterConnDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCredin_Work_Center(Credin_Work_Center instance);
    partial void UpdateCredin_Work_Center(Credin_Work_Center instance);
    partial void DeleteCredin_Work_Center(Credin_Work_Center instance);
    #endregion
		
		public WorkCenterConnDataContext() : 
				base(global::WindowsFormsApplication1.Properties.Settings.Default.TEST_NAVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WorkCenterConnDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WorkCenterConnDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WorkCenterConnDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WorkCenterConnDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Credin_Work_Center> Credin_Work_Centers
		{
			get
			{
				return this.GetTable<Credin_Work_Center>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Credin$Work Center]")]
	public partial class Credin_Work_Center : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Data.Linq.Binary _timestamp;
		
		private string _No_;
		
		private string _Name;
		
		private string _Search_Name;
		
		private string _Name_2;
		
		private string _Address;
		
		private string _Address_2;
		
		private string _City;
		
		private string _Post_Code;
		
		private string _Alternate_Work_Center;
		
		private string _Work_Center_Group_Code;
		
		private string _Global_Dimension_1_Code;
		
		private string _Global_Dimension_2_Code;
		
		private string _Subcontractor_No_;
		
		private decimal _Direct_Unit_Cost;
		
		private decimal _Indirect_Cost__;
		
		private decimal _Unit_Cost;
		
		private decimal _Queue_Time;
		
		private string _Queue_Time_Unit_of_Meas__Code;
		
		private System.DateTime _Last_Date_Modified;
		
		private string _Unit_of_Measure_Code;
		
		private decimal _Capacity;
		
		private decimal _Efficiency;
		
		private decimal _Maximum_Efficiency;
		
		private decimal _Minimum_Efficiency;
		
		private decimal _Calendar_Rounding_Precision;
		
		private int _Simulation_Type;
		
		private string _Shop_Calendar_Code;
		
		private byte _Blocked;
		
		private int _Unit_Cost_Calculation;
		
		private byte _Specific_Unit_Cost;
		
		private byte _Consolidated_Calendar;
		
		private int _Flushing_Method;
		
		private string _No__Series;
		
		private decimal _Overhead_Rate;
		
		private string _Gen__Prod__Posting_Group;
		
		private string _County;
		
		private string _Country_Code;
		
		private byte _Vis_i_afgangsvindue;
		
		private string _Terminal_reg__no_;
		
		private byte _Registrer_vægt_fra_Anlæg;
		
		private int _Sortering;
		
		private byte _Manuel_Produktionsrækkefølge;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntimestampChanging(System.Data.Linq.Binary value);
    partial void OntimestampChanged();
    partial void OnNo_Changing(string value);
    partial void OnNo_Changed();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSearch_NameChanging(string value);
    partial void OnSearch_NameChanged();
    partial void OnName_2Changing(string value);
    partial void OnName_2Changed();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnAddress_2Changing(string value);
    partial void OnAddress_2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnPost_CodeChanging(string value);
    partial void OnPost_CodeChanged();
    partial void OnAlternate_Work_CenterChanging(string value);
    partial void OnAlternate_Work_CenterChanged();
    partial void OnWork_Center_Group_CodeChanging(string value);
    partial void OnWork_Center_Group_CodeChanged();
    partial void OnGlobal_Dimension_1_CodeChanging(string value);
    partial void OnGlobal_Dimension_1_CodeChanged();
    partial void OnGlobal_Dimension_2_CodeChanging(string value);
    partial void OnGlobal_Dimension_2_CodeChanged();
    partial void OnSubcontractor_No_Changing(string value);
    partial void OnSubcontractor_No_Changed();
    partial void OnDirect_Unit_CostChanging(decimal value);
    partial void OnDirect_Unit_CostChanged();
    partial void OnIndirect_Cost__Changing(decimal value);
    partial void OnIndirect_Cost__Changed();
    partial void OnUnit_CostChanging(decimal value);
    partial void OnUnit_CostChanged();
    partial void OnQueue_TimeChanging(decimal value);
    partial void OnQueue_TimeChanged();
    partial void OnQueue_Time_Unit_of_Meas__CodeChanging(string value);
    partial void OnQueue_Time_Unit_of_Meas__CodeChanged();
    partial void OnLast_Date_ModifiedChanging(System.DateTime value);
    partial void OnLast_Date_ModifiedChanged();
    partial void OnUnit_of_Measure_CodeChanging(string value);
    partial void OnUnit_of_Measure_CodeChanged();
    partial void OnCapacityChanging(decimal value);
    partial void OnCapacityChanged();
    partial void OnEfficiencyChanging(decimal value);
    partial void OnEfficiencyChanged();
    partial void OnMaximum_EfficiencyChanging(decimal value);
    partial void OnMaximum_EfficiencyChanged();
    partial void OnMinimum_EfficiencyChanging(decimal value);
    partial void OnMinimum_EfficiencyChanged();
    partial void OnCalendar_Rounding_PrecisionChanging(decimal value);
    partial void OnCalendar_Rounding_PrecisionChanged();
    partial void OnSimulation_TypeChanging(int value);
    partial void OnSimulation_TypeChanged();
    partial void OnShop_Calendar_CodeChanging(string value);
    partial void OnShop_Calendar_CodeChanged();
    partial void OnBlockedChanging(byte value);
    partial void OnBlockedChanged();
    partial void OnUnit_Cost_CalculationChanging(int value);
    partial void OnUnit_Cost_CalculationChanged();
    partial void OnSpecific_Unit_CostChanging(byte value);
    partial void OnSpecific_Unit_CostChanged();
    partial void OnConsolidated_CalendarChanging(byte value);
    partial void OnConsolidated_CalendarChanged();
    partial void OnFlushing_MethodChanging(int value);
    partial void OnFlushing_MethodChanged();
    partial void OnNo__SeriesChanging(string value);
    partial void OnNo__SeriesChanged();
    partial void OnOverhead_RateChanging(decimal value);
    partial void OnOverhead_RateChanged();
    partial void OnGen__Prod__Posting_GroupChanging(string value);
    partial void OnGen__Prod__Posting_GroupChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnCountry_CodeChanging(string value);
    partial void OnCountry_CodeChanged();
    partial void OnVis_i_afgangsvindueChanging(byte value);
    partial void OnVis_i_afgangsvindueChanged();
    partial void OnTerminal_reg__no_Changing(string value);
    partial void OnTerminal_reg__no_Changed();
    partial void OnRegistrer_vægt_fra_AnlægChanging(byte value);
    partial void OnRegistrer_vægt_fra_AnlægChanged();
    partial void OnSorteringChanging(int value);
    partial void OnSorteringChanged();
    partial void OnManuel_ProduktionsrækkefølgeChanging(byte value);
    partial void OnManuel_ProduktionsrækkefølgeChanged();
    #endregion
		
		public Credin_Work_Center()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string No_
		{
			get
			{
				return this._No_;
			}
			set
			{
				if ((this._No_ != value))
				{
					this.OnNo_Changing(value);
					this.SendPropertyChanging();
					this._No_ = value;
					this.SendPropertyChanged("No_");
					this.OnNo_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Search Name]", Storage="_Search_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Search_Name
		{
			get
			{
				return this._Search_Name;
			}
			set
			{
				if ((this._Search_Name != value))
				{
					this.OnSearch_NameChanging(value);
					this.SendPropertyChanging();
					this._Search_Name = value;
					this.SendPropertyChanged("Search_Name");
					this.OnSearch_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Name 2]", Storage="_Name_2", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Name_2
		{
			get
			{
				return this._Name_2;
			}
			set
			{
				if ((this._Name_2 != value))
				{
					this.OnName_2Changing(value);
					this.SendPropertyChanging();
					this._Name_2 = value;
					this.SendPropertyChanged("Name_2");
					this.OnName_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Address 2]", Storage="_Address_2", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Address_2
		{
			get
			{
				return this._Address_2;
			}
			set
			{
				if ((this._Address_2 != value))
				{
					this.OnAddress_2Changing(value);
					this.SendPropertyChanging();
					this._Address_2 = value;
					this.SendPropertyChanged("Address_2");
					this.OnAddress_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Post Code]", Storage="_Post_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Post_Code
		{
			get
			{
				return this._Post_Code;
			}
			set
			{
				if ((this._Post_Code != value))
				{
					this.OnPost_CodeChanging(value);
					this.SendPropertyChanging();
					this._Post_Code = value;
					this.SendPropertyChanged("Post_Code");
					this.OnPost_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Alternate Work Center]", Storage="_Alternate_Work_Center", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Alternate_Work_Center
		{
			get
			{
				return this._Alternate_Work_Center;
			}
			set
			{
				if ((this._Alternate_Work_Center != value))
				{
					this.OnAlternate_Work_CenterChanging(value);
					this.SendPropertyChanging();
					this._Alternate_Work_Center = value;
					this.SendPropertyChanged("Alternate_Work_Center");
					this.OnAlternate_Work_CenterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Work Center Group Code]", Storage="_Work_Center_Group_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Work_Center_Group_Code
		{
			get
			{
				return this._Work_Center_Group_Code;
			}
			set
			{
				if ((this._Work_Center_Group_Code != value))
				{
					this.OnWork_Center_Group_CodeChanging(value);
					this.SendPropertyChanging();
					this._Work_Center_Group_Code = value;
					this.SendPropertyChanged("Work_Center_Group_Code");
					this.OnWork_Center_Group_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Global Dimension 1 Code]", Storage="_Global_Dimension_1_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Global_Dimension_1_Code
		{
			get
			{
				return this._Global_Dimension_1_Code;
			}
			set
			{
				if ((this._Global_Dimension_1_Code != value))
				{
					this.OnGlobal_Dimension_1_CodeChanging(value);
					this.SendPropertyChanging();
					this._Global_Dimension_1_Code = value;
					this.SendPropertyChanged("Global_Dimension_1_Code");
					this.OnGlobal_Dimension_1_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Global Dimension 2 Code]", Storage="_Global_Dimension_2_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Global_Dimension_2_Code
		{
			get
			{
				return this._Global_Dimension_2_Code;
			}
			set
			{
				if ((this._Global_Dimension_2_Code != value))
				{
					this.OnGlobal_Dimension_2_CodeChanging(value);
					this.SendPropertyChanging();
					this._Global_Dimension_2_Code = value;
					this.SendPropertyChanged("Global_Dimension_2_Code");
					this.OnGlobal_Dimension_2_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Subcontractor No_]", Storage="_Subcontractor_No_", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Subcontractor_No_
		{
			get
			{
				return this._Subcontractor_No_;
			}
			set
			{
				if ((this._Subcontractor_No_ != value))
				{
					this.OnSubcontractor_No_Changing(value);
					this.SendPropertyChanging();
					this._Subcontractor_No_ = value;
					this.SendPropertyChanged("Subcontractor_No_");
					this.OnSubcontractor_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Direct Unit Cost]", Storage="_Direct_Unit_Cost", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Direct_Unit_Cost
		{
			get
			{
				return this._Direct_Unit_Cost;
			}
			set
			{
				if ((this._Direct_Unit_Cost != value))
				{
					this.OnDirect_Unit_CostChanging(value);
					this.SendPropertyChanging();
					this._Direct_Unit_Cost = value;
					this.SendPropertyChanged("Direct_Unit_Cost");
					this.OnDirect_Unit_CostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Indirect Cost %]", Storage="_Indirect_Cost__", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Indirect_Cost__
		{
			get
			{
				return this._Indirect_Cost__;
			}
			set
			{
				if ((this._Indirect_Cost__ != value))
				{
					this.OnIndirect_Cost__Changing(value);
					this.SendPropertyChanging();
					this._Indirect_Cost__ = value;
					this.SendPropertyChanged("Indirect_Cost__");
					this.OnIndirect_Cost__Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Unit Cost]", Storage="_Unit_Cost", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Unit_Cost
		{
			get
			{
				return this._Unit_Cost;
			}
			set
			{
				if ((this._Unit_Cost != value))
				{
					this.OnUnit_CostChanging(value);
					this.SendPropertyChanging();
					this._Unit_Cost = value;
					this.SendPropertyChanged("Unit_Cost");
					this.OnUnit_CostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Queue Time]", Storage="_Queue_Time", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Queue_Time
		{
			get
			{
				return this._Queue_Time;
			}
			set
			{
				if ((this._Queue_Time != value))
				{
					this.OnQueue_TimeChanging(value);
					this.SendPropertyChanging();
					this._Queue_Time = value;
					this.SendPropertyChanged("Queue_Time");
					this.OnQueue_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Queue Time Unit of Meas_ Code]", Storage="_Queue_Time_Unit_of_Meas__Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Queue_Time_Unit_of_Meas__Code
		{
			get
			{
				return this._Queue_Time_Unit_of_Meas__Code;
			}
			set
			{
				if ((this._Queue_Time_Unit_of_Meas__Code != value))
				{
					this.OnQueue_Time_Unit_of_Meas__CodeChanging(value);
					this.SendPropertyChanging();
					this._Queue_Time_Unit_of_Meas__Code = value;
					this.SendPropertyChanged("Queue_Time_Unit_of_Meas__Code");
					this.OnQueue_Time_Unit_of_Meas__CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Date Modified]", Storage="_Last_Date_Modified", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Last_Date_Modified
		{
			get
			{
				return this._Last_Date_Modified;
			}
			set
			{
				if ((this._Last_Date_Modified != value))
				{
					this.OnLast_Date_ModifiedChanging(value);
					this.SendPropertyChanging();
					this._Last_Date_Modified = value;
					this.SendPropertyChanged("Last_Date_Modified");
					this.OnLast_Date_ModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Unit of Measure Code]", Storage="_Unit_of_Measure_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Unit_of_Measure_Code
		{
			get
			{
				return this._Unit_of_Measure_Code;
			}
			set
			{
				if ((this._Unit_of_Measure_Code != value))
				{
					this.OnUnit_of_Measure_CodeChanging(value);
					this.SendPropertyChanging();
					this._Unit_of_Measure_Code = value;
					this.SendPropertyChanged("Unit_of_Measure_Code");
					this.OnUnit_of_Measure_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this.OnCapacityChanging(value);
					this.SendPropertyChanging();
					this._Capacity = value;
					this.SendPropertyChanged("Capacity");
					this.OnCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Efficiency", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Efficiency
		{
			get
			{
				return this._Efficiency;
			}
			set
			{
				if ((this._Efficiency != value))
				{
					this.OnEfficiencyChanging(value);
					this.SendPropertyChanging();
					this._Efficiency = value;
					this.SendPropertyChanged("Efficiency");
					this.OnEfficiencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Maximum Efficiency]", Storage="_Maximum_Efficiency", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Maximum_Efficiency
		{
			get
			{
				return this._Maximum_Efficiency;
			}
			set
			{
				if ((this._Maximum_Efficiency != value))
				{
					this.OnMaximum_EfficiencyChanging(value);
					this.SendPropertyChanging();
					this._Maximum_Efficiency = value;
					this.SendPropertyChanged("Maximum_Efficiency");
					this.OnMaximum_EfficiencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Minimum Efficiency]", Storage="_Minimum_Efficiency", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Minimum_Efficiency
		{
			get
			{
				return this._Minimum_Efficiency;
			}
			set
			{
				if ((this._Minimum_Efficiency != value))
				{
					this.OnMinimum_EfficiencyChanging(value);
					this.SendPropertyChanging();
					this._Minimum_Efficiency = value;
					this.SendPropertyChanged("Minimum_Efficiency");
					this.OnMinimum_EfficiencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Calendar Rounding Precision]", Storage="_Calendar_Rounding_Precision", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Calendar_Rounding_Precision
		{
			get
			{
				return this._Calendar_Rounding_Precision;
			}
			set
			{
				if ((this._Calendar_Rounding_Precision != value))
				{
					this.OnCalendar_Rounding_PrecisionChanging(value);
					this.SendPropertyChanging();
					this._Calendar_Rounding_Precision = value;
					this.SendPropertyChanged("Calendar_Rounding_Precision");
					this.OnCalendar_Rounding_PrecisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Simulation Type]", Storage="_Simulation_Type", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Simulation_Type
		{
			get
			{
				return this._Simulation_Type;
			}
			set
			{
				if ((this._Simulation_Type != value))
				{
					this.OnSimulation_TypeChanging(value);
					this.SendPropertyChanging();
					this._Simulation_Type = value;
					this.SendPropertyChanged("Simulation_Type");
					this.OnSimulation_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Shop Calendar Code]", Storage="_Shop_Calendar_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Shop_Calendar_Code
		{
			get
			{
				return this._Shop_Calendar_Code;
			}
			set
			{
				if ((this._Shop_Calendar_Code != value))
				{
					this.OnShop_Calendar_CodeChanging(value);
					this.SendPropertyChanging();
					this._Shop_Calendar_Code = value;
					this.SendPropertyChanged("Shop_Calendar_Code");
					this.OnShop_Calendar_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blocked", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Blocked
		{
			get
			{
				return this._Blocked;
			}
			set
			{
				if ((this._Blocked != value))
				{
					this.OnBlockedChanging(value);
					this.SendPropertyChanging();
					this._Blocked = value;
					this.SendPropertyChanged("Blocked");
					this.OnBlockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Unit Cost Calculation]", Storage="_Unit_Cost_Calculation", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Unit_Cost_Calculation
		{
			get
			{
				return this._Unit_Cost_Calculation;
			}
			set
			{
				if ((this._Unit_Cost_Calculation != value))
				{
					this.OnUnit_Cost_CalculationChanging(value);
					this.SendPropertyChanging();
					this._Unit_Cost_Calculation = value;
					this.SendPropertyChanged("Unit_Cost_Calculation");
					this.OnUnit_Cost_CalculationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Specific Unit Cost]", Storage="_Specific_Unit_Cost", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Specific_Unit_Cost
		{
			get
			{
				return this._Specific_Unit_Cost;
			}
			set
			{
				if ((this._Specific_Unit_Cost != value))
				{
					this.OnSpecific_Unit_CostChanging(value);
					this.SendPropertyChanging();
					this._Specific_Unit_Cost = value;
					this.SendPropertyChanged("Specific_Unit_Cost");
					this.OnSpecific_Unit_CostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Consolidated Calendar]", Storage="_Consolidated_Calendar", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Consolidated_Calendar
		{
			get
			{
				return this._Consolidated_Calendar;
			}
			set
			{
				if ((this._Consolidated_Calendar != value))
				{
					this.OnConsolidated_CalendarChanging(value);
					this.SendPropertyChanging();
					this._Consolidated_Calendar = value;
					this.SendPropertyChanged("Consolidated_Calendar");
					this.OnConsolidated_CalendarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Flushing Method]", Storage="_Flushing_Method", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Flushing_Method
		{
			get
			{
				return this._Flushing_Method;
			}
			set
			{
				if ((this._Flushing_Method != value))
				{
					this.OnFlushing_MethodChanging(value);
					this.SendPropertyChanging();
					this._Flushing_Method = value;
					this.SendPropertyChanged("Flushing_Method");
					this.OnFlushing_MethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[No_ Series]", Storage="_No__Series", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string No__Series
		{
			get
			{
				return this._No__Series;
			}
			set
			{
				if ((this._No__Series != value))
				{
					this.OnNo__SeriesChanging(value);
					this.SendPropertyChanging();
					this._No__Series = value;
					this.SendPropertyChanged("No__Series");
					this.OnNo__SeriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Overhead Rate]", Storage="_Overhead_Rate", DbType="Decimal(38,20) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Overhead_Rate
		{
			get
			{
				return this._Overhead_Rate;
			}
			set
			{
				if ((this._Overhead_Rate != value))
				{
					this.OnOverhead_RateChanging(value);
					this.SendPropertyChanging();
					this._Overhead_Rate = value;
					this.SendPropertyChanged("Overhead_Rate");
					this.OnOverhead_RateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Gen_ Prod_ Posting Group]", Storage="_Gen__Prod__Posting_Group", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Gen__Prod__Posting_Group
		{
			get
			{
				return this._Gen__Prod__Posting_Group;
			}
			set
			{
				if ((this._Gen__Prod__Posting_Group != value))
				{
					this.OnGen__Prod__Posting_GroupChanging(value);
					this.SendPropertyChanging();
					this._Gen__Prod__Posting_Group = value;
					this.SendPropertyChanged("Gen__Prod__Posting_Group");
					this.OnGen__Prod__Posting_GroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Country Code]", Storage="_Country_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Country_Code
		{
			get
			{
				return this._Country_Code;
			}
			set
			{
				if ((this._Country_Code != value))
				{
					this.OnCountry_CodeChanging(value);
					this.SendPropertyChanging();
					this._Country_Code = value;
					this.SendPropertyChanged("Country_Code");
					this.OnCountry_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vis i afgangsvindue]", Storage="_Vis_i_afgangsvindue", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Vis_i_afgangsvindue
		{
			get
			{
				return this._Vis_i_afgangsvindue;
			}
			set
			{
				if ((this._Vis_i_afgangsvindue != value))
				{
					this.OnVis_i_afgangsvindueChanging(value);
					this.SendPropertyChanging();
					this._Vis_i_afgangsvindue = value;
					this.SendPropertyChanged("Vis_i_afgangsvindue");
					this.OnVis_i_afgangsvindueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Terminal reg_ no_]", Storage="_Terminal_reg__no_", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Terminal_reg__no_
		{
			get
			{
				return this._Terminal_reg__no_;
			}
			set
			{
				if ((this._Terminal_reg__no_ != value))
				{
					this.OnTerminal_reg__no_Changing(value);
					this.SendPropertyChanging();
					this._Terminal_reg__no_ = value;
					this.SendPropertyChanged("Terminal_reg__no_");
					this.OnTerminal_reg__no_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Registrer vægt fra Anlæg]", Storage="_Registrer_vægt_fra_Anlæg", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Registrer_vægt_fra_Anlæg
		{
			get
			{
				return this._Registrer_vægt_fra_Anlæg;
			}
			set
			{
				if ((this._Registrer_vægt_fra_Anlæg != value))
				{
					this.OnRegistrer_vægt_fra_AnlægChanging(value);
					this.SendPropertyChanging();
					this._Registrer_vægt_fra_Anlæg = value;
					this.SendPropertyChanged("Registrer_vægt_fra_Anlæg");
					this.OnRegistrer_vægt_fra_AnlægChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sortering", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Sortering
		{
			get
			{
				return this._Sortering;
			}
			set
			{
				if ((this._Sortering != value))
				{
					this.OnSorteringChanging(value);
					this.SendPropertyChanging();
					this._Sortering = value;
					this.SendPropertyChanged("Sortering");
					this.OnSorteringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Manuel Produktionsrækkefølge]", Storage="_Manuel_Produktionsrækkefølge", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Manuel_Produktionsrækkefølge
		{
			get
			{
				return this._Manuel_Produktionsrækkefølge;
			}
			set
			{
				if ((this._Manuel_Produktionsrækkefølge != value))
				{
					this.OnManuel_ProduktionsrækkefølgeChanging(value);
					this.SendPropertyChanging();
					this._Manuel_Produktionsrækkefølge = value;
					this.SendPropertyChanged("Manuel_Produktionsrækkefølge");
					this.OnManuel_ProduktionsrækkefølgeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
